In [4]:
import h5py
import matplotlib.pyplot as plt
import os
from os import listdir
from mpl_toolkits import mplot3d
import matplotlib.gridspec as gridspec
import numpy as np
import re

axisScale = 0.03
datasets = ['organic', 'gm_late', 'gm_early']

for dataset in datasets:
    print('-----------------------------------------')
    print(dataset)
    print('-----------------------------------------')
    
    files = listdir('C:\\Users\\katha\\GalaxyMorphology\\' + dataset)
    os.path.join("/C:", "Users","katha","GalaxyMorphology", dataset)

    count = 0

    galaxyAm = np.array(range(96), dtype=float).reshape(24,4)
    
    for file in files:
    #if 1==1:



        #file = 'star_particles_015_z002p012.hdf5'
        #file = 'star_particles_028_z000p000.hdf5'
        
        # get redshift from the filename
        m = re.search('(z[0-9])\w+', file)
        s = m.group(0).replace('z', '')
        s = s.replace('p', '.')
        redshift = float(s)
        
        # load data for a particular galaxy at a particular redshift
        f = h5py.File('C:\\Users\\katha\\GalaxyMorphology\\' + dataset + '/' + file,'r')

        # extract date from the file
        ds_c = f['Coordinates']
        ds_v = f['Velocity']
        ds_m = f['Mass']
    

        # Calculate the resultant angular momentum vectors j
        # j contains the AM vectors for each particle per redshift era
        j = np.cross(ds_c, ds_v)
        specAngMom = np.transpose(np.multiply(ds_m, np.transpose(j)))
        specAngMomTot = np.sum(specAngMom, axis=0)/(np.sum(ds_m))
        specAngMomTotMag = np.linalg.norm(specAngMomTot)
        print(np.shape(j))
        print(np.shape(specAngMom))
        print(np.shape(specAngMomTot))
        print(np.shape(specAngMomTotMag))
        
       
        # Calculate the scale factor by working out the angular momentum 
        unitVect_z = specAngMomTot / specAngMomTotMag
        print (unitVect_z)
        print (np.linalg.norm(unitVect_z))
        
        # Calculate y and z

        #angMomTot2 = 
        #print ("angMomTot: ", file, angMomTot)
        #rTot = rTot + r

        # Store totals of all particles for each redshift in the current galaxy
        galaxyAm[count, 0] = redshift
        #galaxyAm[count, 1] = r[]
              
        count = count + 1
        print ('-------------------------------------------------')
    
    # print each angular momentum component's total per redshift
    for n in range(24):
        print('Galaxy "' + dataset + '" redshift: ' + str(galaxyAm[n][3]) + '\t total:  k1:' + str(galaxyAm[n][0]) + '\t k2:' + str(galaxyAm[n][1]) + '\t k3:' + str(galaxyAm[n][2]))
        print('Galaxy "' + dataset + '" redshift: ' + str(galaxyAm[n][0]) + '\t j1: ' + (str(-galaxyAm[n][1] / galaxyAm[n][0]))) + "\t normalised: "
              
    #print ('length: ' + str(np.shape(galaxyAm)[0]))
    #plt.plot(galaxyAm[0:,3], galaxyAm[0:,2])
    plt.plot(galaxyAm[0:,0], galaxyAm[0:,1])

    plt.title('Galaxy: ' + dataset + ' - Magnitude of Angular Momentum vs. Redshift', pad=30)
    plt.xlabel('Redshift')
    plt.ylabel(r'L Magnitude ($M_\odot\ Mpc km s^{-1})$')
    plt.ticklabel_format(axis='y', style='sci', useMathText=True)
    plt.rcParams["figure.figsize"] = (12,10)
    plt.semilogy()
    plt.show()

-----------------------------------------
organic
-----------------------------------------
(34, 3)
(34, 3)
(3,)
()
[0.9515281  0.30598536 0.0311003 ]
0.9999999999999999
-------------------------------------------------
(56, 3)
(56, 3)
(3,)
()
[ 0.65267355 -0.15264495  0.74210293]
1.0
-------------------------------------------------
(129, 3)
(129, 3)
(3,)
()
[ 0.28733915  0.50012508 -0.81689113]
1.0
-------------------------------------------------
(144, 3)
(144, 3)
(3,)
()
[-0.0927266   0.99391521  0.05945022]
1.0
-------------------------------------------------
(158, 3)
(158, 3)
(3,)
()
[-0.10765651  0.98838324 -0.10727835]
1.0
-------------------------------------------------
(221, 3)
(221, 3)
(3,)
()
[0.80910861 0.42998242 0.40057256]
1.0
-------------------------------------------------
(305, 3)
(305, 3)
(3,)
()
[ 0.80743116 -0.49037168 -0.32800997]
1.0
-------------------------------------------------
(756, 3)
(756, 3)
(3,)
()
[-0.24875304  0.17710399 -0.95223742]
1.0
---------

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'